STA_IF: int

class WLAN:
    def __init__(self, interface: int) -> None: ...
    def active(self, state: bool) -> None: ...
    def connect(self, ssid: str, password: str) -> None: ...
    def isconnected(self) -> bool: ...
    def ifconfig(self) -> tuple[str, str, str, str]: ...
